### ISSUE TITLE
How to paging? What are the rules limit skip orderBy?

### ISSUE THREAD

**Issue by oldfeel** [asdine/storm#178]
This is my struct:
````
type RecordAlarm struct {
	Id           int64 `storm:"id,increment"`
	DeviceId     int64
	DeviceName   string
	AlarmContent string
	Result       string
	IsUpload     bool
	IsRead       bool
	CreateTime   time.Time
	Judgments    string
}
````

1. When not use OrderBy, Limit(100).Skip(90) return 91-190.

2. When use OrderBy, Limit(100).Skip(90).OrderBy("Id") return 91-100.

3. When use Limit(10).Skip(20).OrderBy("Id"), exit status 2.

````
err = DB.Select().Limit(10).Skip(20).OrderBy("Id").Reverse().Find(&list)
````
````
2017/08/24 09:28:53 sink.go:230: ssink.slice().Len() 12453
2017/08/24 09:28:53 sink.go:231: skip 20
2017/08/24 09:28:53 sink.go:232: limit 10
panic: reflect.Value.Slice: slice index out of bounds

goroutine 1 [running]:
reflect.Value.Slice(0x7a1c60, 0xc420440340, 0x97, 0x14, 0xa, 0x1, 0x0, 0x0)
	/usr/lib/go-1.8/src/reflect/value.go:1566 +0x1fe
github.com/asdine/storm.(*sorter).flush(0xc42008a300, 0x0, 0x0)
	/home/oldfeel/gopath/src/github.com/asdine/storm/sink.go:229 +0x38d
github.com/asdine/storm.(*query).query(0xc420072de0, 0xc4201a80e0, 0xa121c0, 0xc420198a10, 0xc420051c18, 0xc42007c000)
	/home/oldfeel/gopath/src/github.com/asdine/storm/query.go:218 +0x416
github.com/asdine/storm.(*query).runQuery.func1(0xc4201a80e0, 0x85be00, 0xc4201a80e0)
	/home/oldfeel/gopath/src/github.com/asdine/storm/query.go:176 +0x46
github.com/boltdb/bolt.(*DB).View(0xc42019a000, 0xc420051cb8, 0x0, 0x0)
	/home/oldfeel/gopath/src/github.com/boltdb/bolt/db.go:629 +0x9f
github.com/asdine/storm.(*query).runQuery(0xc420072de0, 0xa121c0, 0xc420198a10, 0xc4201427a0, 0xc420198a10)
	/home/oldfeel/gopath/src/github.com/asdine/storm/query.go:177 +0xc4
github.com/asdine/storm.(*query).Find(0xc420072de0, 0x791e80, 0xc4201427a0, 0x1, 0xa146e0)
	/home/oldfeel/gopath/src/github.com/asdine/storm/query.go:104 +0x9a
main.main()
	/home/oldfeel/gopath/src/example/main.go:23 +0x250
exit status 2
````

**Comment by oldfeel** [comment]
This could repair the Limit(10).Skip(20).OrderBy("Id") error

storm/sink.go, line 226

````
		// vvvvvv comment by oldfeel
		// if skip+limit > ssink.slice().Len() || limit < 1 {
		// 	limit = ssink.slice().Len()
		// }
		// ^^^^^^ comment by oldfeel

		// vvvvvv add by oldfeel
		if limit > ssink.slice().Len() || limit < 1 {
			limit = ssink.slice().Len()
		}
		if skip > ssink.slice().Len() {
			skip = ssink.slice().Len()
		}
		// ^^^^^ add by oldfeel
````

**Comment by asdine** [comment]
Thank you ! This is a bug caused by a bad slicing of the returned slice
