### ISSUE TITLE
Is Query.Each read only?

### ISSUE THREAD

**Issue by kmwenja** [asdine/storm#193]
It seems that writing while inside `Query.Each` causes a deadlock due to lock acquisition deep in boltdb:

Example script:
```go
package main

import "github.com/asdine/storm"

type Item struct {
	Id   int `storm:"id,increment"`
	Name string
}

func main() {
	db, err := storm.Open("data.db")
	if err != nil {
		panic(err)
	}

	err = db.Init(&Item{})
	if err != nil {
		panic(err)
	}

	db.Save(&Item{Name: "Royco"})
	db.Save(&Item{Name: "Royco"})
	db.Save(&Item{Name: "Royco"})
	db.Save(&Item{Name: "Royco"})
	db.Save(&Item{Name: "Royco"})
	db.Save(&Item{Name: "Royco"})
	db.Save(&Item{Name: "Royco"})

	err = db.Select().Each(&Item{}, func(record interface{}) error {
		i := record.(*Item)
		i.Name = "Blueband"
		return db.Save(i)
	})

	if err != nil {
		panic(err)
	}

	var all []*Item
	err = db.All(&all)
	if err != nil {
		panic(err)
	}
	println(all)
}
```
Stacktrace:
```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc42007e190)
	/usr/lib/go/src/runtime/sema.go:56 +0x39
sync.(*RWMutex).Lock(0xc42007e188)
	/usr/lib/go/src/sync/rwmutex.go:98 +0x6e
github.com/boltdb/bolt.(*DB).mmap(0xc42007e000, 0x10000, 0x0, 0x0)
	/..../Projects/Go/src/github.com/boltdb/bolt/db.go:246 +0x5b
github.com/boltdb/bolt.(*DB).allocate(0xc42007e000, 0x1, 0xc420041880, 0x4d098b, 0xc4200622d0)
	/..../Projects/Go/src/github.com/boltdb/bolt/db.go:849 +0x12f
github.com/boltdb/bolt.(*Tx).allocate(0xc420086a80, 0x1, 0x7f6243fb9000, 0xe0e, 0x0)
	/..../Projects/Go/src/github.com/boltdb/bolt/tx.go:456 +0x3d
github.com/boltdb/bolt.(*Tx).Commit(0xc420086a80, 0x0, 0x0)
	/..../Projects/Go/src/github.com/boltdb/bolt/tx.go:177 +0x265
github.com/boltdb/bolt.(*DB).Update(0xc42007e000, 0xc420041a60, 0x0, 0x0)
	/..../Projects/Go/src/github.com/boltdb/bolt/db.go:605 +0xf2
github.com/asdine/storm.(*node).readWriteTx(0xc420052040, 0xc420063890, 0x0, 0x0)
	/..../Projects/Go/src/github.com/asdine/storm/node.go:111 +0xfe
github.com/asdine/storm.(*node).Save(0xc420052040, 0x5655c0, 0xc42000bfc0, 0xc420052b40, 0x7f6244022b48)
	/..../Projects/Go/src/github.com/asdine/storm/store.go:160 +0x1e1
github.com/asdine/storm.(*DB).Save(0xc42007c000, 0x5655c0, 0xc42000bfc0, 0x51f301, 0x5655c0)
	/..../Projects/Go/src/github.com/asdine/storm/storm.go:167 +0x43
main.main.func1(0x5655c0, 0xc42000bfc0, 0x16, 0x5655c0)
	/tmp/ras/main.go:32 +0x73
github.com/asdine/storm.(*eachSink).add(0xc420063650, 0xc420052b40, 0xc42000bfc0, 0x565501, 0x0)
	/..../Projects/Go/src/github.com/asdine/storm/sink.go:501 +0x92
github.com/asdine/storm.(*sorter).filter(0xc4200529c0, 0x67e700, 0xc420063650, 0x67d500, 0xc42000bc00, 0xc420052a00, 0x7f6243fb30af, 0x8, 0x8, 0x7f6243fb30b7, ...)
	/..../Projects/Go/src/github.com/asdine/storm/sink.go:89 +0x5ea
github.com/asdine/storm.(*query).query(0xc420068230, 0xc4200868c0, 0x67e700, 0xc420063650, 0xc420041de0, 0x0)
	/..../Projects/Go/src/github.com/asdine/storm/query.go:219 +0x299
github.com/asdine/storm.(*query).runQuery.func1(0xc4200868c0, 0x5b5548, 0xc4200868c0)
	/..../Projects/Go/src/github.com/asdine/storm/query.go:193 +0x46
github.com/boltdb/bolt.(*DB).View(0xc42007e000, 0xc420041e78, 0x0, 0x0)
	/..../Projects/Go/src/github.com/boltdb/bolt/db.go:629 +0x9a
github.com/asdine/storm.(*query).runQuery(0xc420068230, 0x67e700, 0xc420063650, 0x0, 0x0)
	/..../Projects/Go/src/github.com/asdine/storm/query.go:192 +0xb7
github.com/asdine/storm.(*query).Each(0xc420068230, 0x5655c0, 0xc42000bc40, 0xc42000e6d0, 0x67fa60, 0xc420068230)
	/..../Projects/Go/src/github.com/asdine/storm/query.go:184 +0x95
main.main()
	/tmp/ras/main.go:29 +0x411
exit status 2
```
*Aside: Thanks for storm. It makes working with boltdb a heck of a lot easier.*

**Comment by asdine** [comment]
Yes except for `Delete`, all the methods of `Select` are read-only by default.
But your use case seems legit to me so maybe we should add a way to specify if we want write access or not.

**Comment by kmwenja** [comment]
Yeah, it would be a really big boon. The alternative (what I'm currently doing) is implementing some sort of paging.
