### ISSUE TITLE
DB.Save() panics if struct with embedded struct is passed by value

### ISSUE THREAD

**Issue by bits01** [asdine/storm#48]
```
type Base struct {
	Ident string `storm:"id"`
}

type User struct {
	Base `storm:"inline"`
	Group     string `storm:"index"`
	Email     string `storm:"unique"`
	Name      string
	CreatedAt time.Time `storm:"index"`
}

func main() {
	db, err := storm.Open("my.db")
	if err != nil {
		log.Fatal("db open:", err)
	}
	defer db.Close()

	user := User{
		Base:      Base{Ident: "10"},
		Group:     "staff",
		Email:     "john@provider.com",
		Name:      "John",
		CreatedAt: time.Now(),
	}

	if err = db.Save(user); err != nil {
		log.Fatal("save user:", err)
	}
```

```
panic: reflect.Value.Addr of unaddressable value

goroutine 1 [running]:
panic(0x1275e0, 0xc8200687c0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
reflect.Value.Addr(0x15cd40, 0xc8200a2120, 0x99, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:240 +0x8c
github.com/asdine/storm.extractField(0xc82008ea80, 0xc820094070, 0xc820093140, 0x0, 0x0, 0x0)
	/Users/x/code/go/src/github.com/asdine/storm/extract.go:150 +0xa99
github.com/asdine/storm.extract(0x1724e0, 0xc8200a2120, 0x0, 0x0, 0x0, 0xc81fffaef9, 0x0, 0x0)
	/Users/x/code/go/src/github.com/asdine/storm/extract.go:102 +0xa37
github.com/asdine/storm.(*Node).Save(0xc82006c8a0, 0x1724e0, 0xc8200a2120, 0x0, 0x0)
	/Users/x/code/go/src/github.com/asdine/storm/save.go:12 +0x63
github.com/asdine/storm.(*DB).Save(0xc8200a2000, 0x1724e0, 0xc8200a2120, 0x0, 0x0)
	/Users/x/code/go/src/github.com/asdine/storm/save.go:108 +0x45
```

Note `db.Save(user)` rather than `db.Save(&user)` above, an easy mistake to make, if it's even considered a mistake.

`DB.Save()` should probably check and only accept pointers to structs to avoid these cases.
Alternatively `extractField()` should probably check `CanAddr()` first and fail with a more descriptive error.

**Comment by asdine** [comment]
I can reproduce it with a simple struct passed by value. The question is should we only accept pointers to structs or also accept copies?

**Comment by bits01** [comment]
Could you please post an example of a simple struct passed by value that fails? I tried one without any `inline` tags and it worked. 

I think supporting just pointers is fine, for efficiency callers would want to use pointers anyway instead of making copies of potentially large structs.

**Comment by asdine** [comment]
Here is one:
```go
w := User{Name: "John"}
err := db.Save(w)
assert.Error(t, err)
assert.Equal(t, ErrStructPtrNeeded, err)
```

**Comment by bits01** [comment]
What is the struct definition of `User` in your example above? Just like the one in my bug report above?

**Comment by asdine** [comment]
It is a simple struct that you can find [here](https://github.com/asdine/storm/blob/master/structs_test.go#L64) and that i use for several tests

**Comment by bits01** [comment]
Thanks for the fix. Interesting that I can't get it to fail with your simple User struct.

Here's what I tried before the fix and it worked fine for me. It worries me if it failed for you but not for me.

```
package main

import (
	"log"
	"time"

	"github.com/asdine/storm"
)

type User struct {
	ID          int    `storm:"id"`
	Name        string `storm:"index"`
	age         int
	DateOfBirth time.Time `storm:"index"`
	Group       string
	Slug        string `storm:"unique"`
}

func main() {
	db, err := storm.Open("my.db")
	if err != nil {
		log.Fatal("db open:", err)
	}
	defer db.Close()

	user := User{ID: 20, Name: "John"}

	if err = db.Save(user); err != nil {
		log.Fatal("save user: ", err)
	}
}
```

**Comment by asdine** [comment]
Sorry, i does not fail for me either but this fails:

```go
package main

import (
	"log"
	"time"

	"github.com/asdine/storm"
)

type User struct {
	ID          int    `storm:"id"`
	Name        string `storm:"index"`
	age         int
	DateOfBirth time.Time `storm:"index"`
	Group       string
	Slug        string `storm:"unique"`
}

func main() {
	db, err := storm.Open("my.db", storm.AutoIncrement())
	if err != nil {
		log.Fatal("db open:", err)
	}
	defer db.Close()

	user := User{Name: "John"}

	if err = db.Save(user); err != nil {
		log.Fatal("save user: ", err)
	}
}
```

The `AutoIncrement` option makes it fail because Storm needs to access the ID field to set the new incremented value

**Comment by bits01** [comment]
Indeed, any required access to a non-addressable field would do.

(The previous example without the AutoIncrement option failed because the ID==0 which is different than the field not being addressable)
